apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: GustavoSzi/${{ values.name }}
spec:
  type: website
  lifecycle: experimental
  owner: devs
